public class Player {
    public void playing(){
        string player1Name = 'John';
        system.debug(Player1Name);
        Integer player1Namelength = player1Name.length();
        system.debug(player1Namelength);
        //system.debug(player1Name.length());
        string upperPlayer1Name = player1Name.toUpperCase();
        system.debug(upperPlayer1Name);

        string player2Name = 'Jack';
        system.debug(player2Name);
        Integer player2Namelength = player2Name.length();
        system.debug(player2Namelength);
        
        
        string player3Name = 'Amy';
        system.debug(PLAYER3Name);
        Integer player3Namelength = player3Name.length();
        system.debug(player3Namelength);
        string upperPlayer3Name = player3Name.toUpperCase();
        system.debug(upperPlayer3Name);

        string player4Name = 'Mary';
        system.debug(player4Name);
        Integer player4Namelength = player4Name.length();
        system.debug(player4Namelength);

        string player5Name = 'William';
        system.debug(player5Name);
        Integer player5Namelength = player5Name.length();
        system.debug(player5Namelength);
    }
}