system.debug(Calculator.dynamicCalulationMethod(10, 67.5, 'ADDITION'));
system.debug(Calculator.dynamicCalulationMethod(10, 67.5, 'addition'));
system.debug(Calculator.dynamicCalulationMethod(90, 60, 'SUBSTRACTION'));
system.debug(Calculator.dynamicCalulationMethod(7.5, 3.5, 'SUBSTRACTION'));
system.debug(Calculator.dynamicCalulationMethod(8, 2, 'DIVISION'));
system.debug(Calculator.dynamicCalulationMethod(6, 4, 'MULTIPLICATION'));